package constants;

import java.util.Map;

public class MarioPartySongNames {

    public static final Map<Integer, String> MARIO_PARTY_5_TRACK_NAMES = Map.ofEntries(
            Map.entry(2, "Title Screen"),
            Map.entry(3, "Inside the Dream"),
            Map.entry(4, "Start of the Dream"),
            Map.entry(5, "Toy Dream"),
            Map.entry(6, "Rainbow Dream"),
            Map.entry(7, "Pirate Dream"),
            Map.entry(8, "Undersea Dream"),
            Map.entry(9, "Future Dream"),
            Map.entry(10, "Sweet Dream"),
            Map.entry(11, "Bowser Nightmare"),
            Map.entry(12, "Tutorial"),
            Map.entry(13, "Dream Country"),
            Map.entry(14, "Star Location"),
            Map.entry(15, "Duel/Battle"),
            Map.entry(16, "Bowser"),
            Map.entry(17, "DK"),
            Map.entry(18, "Doubtful Chance"),
            Map.entry(19, "Flutter"),
            Map.entry(20, "Last 5 Turns"),
            Map.entry(21, "Game Results"),
            Map.entry(24, "Koopa Kid Offspring"),
            Map.entry(25, "Dizzy Head"),
            Map.entry(26, "Bowser's Sour Grapes"),
            Map.entry(27, "What's Your Rank?"),
            Map.entry(28, "Bowser's Scheme"),
            Map.entry(29, "Where to Next?"),
            Map.entry(30, "Chase Bowser"),
            Map.entry(31, "Your Dream Comes True"),
            Map.entry(32, "Everybody's Dream (Credits)"),
            Map.entry(35, "Tournament Minigame"),
            Map.entry(36, "Minigame Circuit"),
            Map.entry(37, "Battle Match"),
            Map.entry(38, "Sign Attack"),
            Map.entry(39, "How about a Card?"),
            Map.entry(40, "Card Party"),
            Map.entry(41, "Super Duel Mode Garage"),
            Map.entry(43, "Burning Challenger"),
            Map.entry(44, "Knock em Out"),
            Map.entry(45, "Plunder"),
            Map.entry(46, "Rabbit"),
            Map.entry(48, "Ready, OK?"),
            Map.entry(49, "Minigame Results"),
            Map.entry(50, "In Great Fear"),
            Map.entry(51, "In Calm Water"),
            Map.entry(52, "Exciting Walk"),
            Map.entry(53, "Everybody Party"),
            Map.entry(54, "Rolling About"),
            Map.entry(55, "Bustling Nosily"),
            Map.entry(57, "Nervous Tension"),
            Map.entry(58, "Danger Abounds"),
            Map.entry(59, "Midday Showdown"),
            Map.entry(60, "Move Happily"),
            Map.entry(61, "DK Chance!"),
            Map.entry(62, "Serious Competition"),
            Map.entry(63, "Bad Bowser Castle"),
            Map.entry(64, "Final Test"),
            Map.entry(65, "Big Bowser Battle!"),
            Map.entry(66, "Pop Star Piranhas 1"),
            Map.entry(67, "Pop Star Piranhas 2"),
            Map.entry(68, "Pop Star Piranhas 3"),
            Map.entry(69, "Dream Memories"),
            Map.entry(70, "Who Won?"),
            Map.entry(71, "Game Winner"),
            Map.entry(72, "End of the Battle"),
            Map.entry(74, "We're the Champs"),
            Map.entry(75, "How Far?"),
            Map.entry(76, "Chain Chomp"),
            Map.entry(77, "Exciting Walk (with Intro)"),
            Map.entry(78, "Everybody Party (Dinger Derby)"),
            Map.entry(79, "Rolling About (Defuse or Lose)"),
            Map.entry(80, "Nervous Tension (with Intro)"),
            Map.entry(81, "Move Happily (with Intro)"),
            Map.entry(82, "Sign Attack (no Intro)"),
            Map.entry(83, "Rolling About (Flatiator)"),
            Map.entry(84, "Everybody Party (with Intro)"),
            Map.entry(85, "Rolling About (Later Skater)"),
            Map.entry(86, "Serious Competition (with Intro)"),
            Map.entry(87, "Bowser Laughs"),
            Map.entry(88, "Rolling About (Will Flower)"),
            Map.entry(89, "In Great Fear (Big Top Drop)"),
            Map.entry(90, "DK again?"),
            Map.entry(91, "Battle/Duel again?"),
            Map.entry(121, "Minigame Winner"),
            Map.entry(122, "Minigame Lose"),
            Map.entry(123, "Tie"),
            Map.entry(126, "Machine Complete"),
            Map.entry(127, "Star Get"),
            Map.entry(128, "A Bit of Happiness"),
            Map.entry(129, "A Lot of Happiness"),
            Map.entry(131, "Battle Wasteland"),
            Map.entry(133, "Start Battle"),
            Map.entry(136, "Sign Attack Intro (for some reason)"),
            Map.entry(137, "Star Get again?"),
            Map.entry(138, "Ztar"),
            Map.entry(139, "Bowser Intro"),
            Map.entry(140, "Super Duel Win")
    );

    public static final Map<Integer, String> MARIO_PARTY_6_TRACK_NAMES = Map.ofEntries(
            Map.entry(0, "Here We Go (Intro)"),
            Map.entry(1, "Party Music (Title Screen)"),
            Map.entry(2, "Setting Up (File Select)"),
            Map.entry(3, "Time to Play (Main Menu)"),
            Map.entry(4, "Brighton and Twila Song (Character Select)"),
            Map.entry(5, "Brighton Theme"),
            Map.entry(6, "Twila Theme"),
            Map.entry(7, "Options Menu"),
            Map.entry(8, "Whoop it Up"),
            Map.entry(9, "Credits"),
            Map.entry(10, "Slow and Steady Sped Up (Block Star)"),
            Map.entry(11, "Board Party (Party Mode Intro)"),
            Map.entry(12, "Star Space"),
            Map.entry(13, "Towering Treetop"),
            Map.entry(14, "Evening Treetop"),
            Map.entry(15, "E Gadd's Garage"),
            Map.entry(16, "Night at the Garage"),
            Map.entry(17, "Faire Square"),
            Map.entry(18, "Square at Night"),
            Map.entry(19, "Snowflake Lake"),
            Map.entry(20, "Snowy Night"),
            Map.entry(21, "Castaway Bay"),
            Map.entry(22, "Night on the Bay"),
            Map.entry(23, "Clockwork Castle"),
            Map.entry(24, "Night at the Castle"),
            Map.entry(25, "Duel/Battle"),
            Map.entry(26, "Duel/Battle (again?)"),
            Map.entry(27, "Bowser Theme"),
            Map.entry(28, "Bowser Theme 2"),
            Map.entry(29, "DK Theme"),
            Map.entry(30, "DK Theme 2"),
            Map.entry(31, "Round of Miracles"),
            Map.entry(32, "Pink Boo"),
            Map.entry(33, "Last 5 Turns"),
            Map.entry(34, "Party's Over"),
            Map.entry(35, "Winner"),
            Map.entry(36, "Champ"),
            Map.entry(37, "Brighton's Explanation"),
            Map.entry(38, "Twila's Explanation"),
            Map.entry(39, "Star Get"),
            Map.entry(40, "Playing Together"),
            Map.entry(41, "Winning Together"),
            Map.entry(42, "Slow and Steady Rave Party? (Block Star)"),
            Map.entry(43, "Block Star Again"),
            Map.entry(45, "Thirsty Gulch"),
            Map.entry(46, "Astro Avenue"),
            Map.entry(47, "Infernal Tower"),
            Map.entry(48, "Solo Mode Results"),
            Map.entry(49, "Solo Mode Lose"),
            Map.entry(50, "Special Gift"),
            Map.entry(51, "Minigame Bus"),
            Map.entry(52, "Battle Bridge"),
            Map.entry(53, "Decathalon Park"),
            Map.entry(54, "Endurance Alley"),
            Map.entry(55, "Treetop Bingo"),
            Map.entry(56, "Really Long Road"),
            Map.entry(57, "Almost Endless Road"),
            Map.entry(58, "Up High"),
            Map.entry(59, "Pushing the Limit"),
            Map.entry(60, "100 Wins in a Row"),
            Map.entry(61, "Long Road"),
            Map.entry(64, "Minigame Explanation"),
            Map.entry(65, "Insectiride Choose"),
            Map.entry(66, "New Record"),
            Map.entry(67, "Minigame Winner"),
            Map.entry(68, "Losing"),
            Map.entry(69, "Tie"),
            Map.entry(70, "Turn Results"),
            Map.entry(71, "E Gadd Maze"),
            Map.entry(72, "Frantic"),
            Map.entry(73, "Jazzy"),
            Map.entry(74, "Doom and Gloom"),
            Map.entry(75, "Tenacious"),
            Map.entry(76, "Blissful"),
            Map.entry(77, "Pumped Up"),
            Map.entry(78, "Laid-back"),
            Map.entry(79, "Relaxed"),
            Map.entry(80, "Slam Dunk"),
            Map.entry(81, "Upbeat"),
            Map.entry(82, "Amusing"),
            Map.entry(83, "Slow and Steady"),
            Map.entry(84, "Fast and Furious"),
            Map.entry(85, "Night Duel"),
            Map.entry(86, "Time to Duel"),
            Map.entry(87, "Duel for Prizes"),
            Map.entry(88, "Gaming with Bowser"),
            Map.entry(89, "Gaming with DK"),
            Map.entry(90, "Seer Terror"),
            Map.entry(91, "Maze Manufactory"),
            Map.entry(92, "Star Bank"),
            Map.entry(93, "Quiz Master"),
            Map.entry(94, "Miracle Book"),
            Map.entry(95, "Speak Up"),
            Map.entry(96, "Quiz Song"),
            Map.entry(97, "Bowser Quiz"),
            Map.entry(99, "Well Done"),
            Map.entry(100, "Mic Question"),
            Map.entry(101, "Mic Question 2"),
            Map.entry(102, "Mic Question 3"),
            Map.entry(103, "Mic Question 4"),
            Map.entry(104, "Mic Question 5"),
            Map.entry(105, "Fun Times"),
            Map.entry(106, "Old School"),
            Map.entry(107, "Meadow Road"),
            Map.entry(108, "Dark Path"),
            Map.entry(109, "Magma Flows")
    );

    public static final Map<Integer, String> MARIO_PARTY_7_TRACK_NAMES = Map.ofEntries(
            Map.entry(0, "Intro"),
            Map.entry(1, "Title Screen"),
            Map.entry(2, "File Select"),
            Map.entry(3, "Main Menu"),
            Map.entry(4, "Character Select"),
            Map.entry(5, "Solo Mode"),
            Map.entry(6, "Options Mode"),
            Map.entry(7, "The Last Hurrah"),
            Map.entry(8, "Credits"),
            Map.entry(9, "Party Mode Intro (start)"),
            Map.entry(10, "Star Location"),
            Map.entry(11, "Grand Canal"),
            Map.entry(12, "Pagoda Peak"),
            Map.entry(13, "Pyramid Park"),
            Map.entry(14, "Neon Heights"),
            Map.entry(15, "Windmillville"),
            Map.entry(16, "Bowser's Enchanted Inferno"),
            Map.entry(17, "Battle Game"),
            Map.entry(18, "Duel"),
            Map.entry(19, "Mic Game"),
            Map.entry(20, "DK"),
            Map.entry(21, "Bowser"),
            Map.entry(22, "Bowser Time"),
            Map.entry(23, "Bowser Theme 2"),
            Map.entry(24, "Minigame Results"),
            Map.entry(26, "Last 4 Turns"),
            Map.entry(27, "Game Results"),
            Map.entry(29, "Who's the Winner?"),
            Map.entry(30, "Hail to the King"),
            Map.entry(31, "Take me to Partytown"),
            Map.entry(32, "Game Start"),
            Map.entry(33, "Bowser's Invitation"),
            Map.entry(37, "Minigame Sub"),
            Map.entry(38, "Volcano Peril"),
            Map.entry(39, "Pearl Hunt"),
            Map.entry(40, "Waterfall Duel"),
            Map.entry(41, "Decathalon Castle"),
            Map.entry(42, "King of the River"),
            Map.entry(44, "King of the River 1"),
            Map.entry(45, "King of the River 2"),
            Map.entry(46, "King of the River 3"),
            Map.entry(47, "King of the River Lose"),
            Map.entry(48, "King of the River Win"),
            Map.entry(49, "King of the River Win (no intro)"),
            Map.entry(50, "Minigame Explanation"),
            Map.entry(51, "Lazy Day Lollygag"),
            Map.entry(52, "Keep it Up"),
            Map.entry(53, "Fun in the Sun"),
            Map.entry(54, "Skyward Bound"),
            Map.entry(55, "Don't Look Down"),
            Map.entry(56, "Slow and Steady"),
            Map.entry(57, "Darkness Rising"),
            Map.entry(58, "What a Mess!"),
            Map.entry(59, "Look Out!"),
            Map.entry(60, "Cool as a Cucumber"),
            Map.entry(61, "Watch Yourself"),
            Map.entry(62, "Without a Care (Mic Game)"),
            Map.entry(64, "Time Grows Nigh"),
            Map.entry(65, "Jump!"),
            Map.entry(66, "Face-Off (Bowser Singleplayer)"),
            Map.entry(67, "Bowser Multiplayer Game"),
            Map.entry(68, "DK Singleplayer"),
            Map.entry(69, "DK Multiplayer"),
            Map.entry(70, "High Noon"),
            Map.entry(71, "One Last Go"),
            Map.entry(72, "Rare Minigame"),
            Map.entry(73, "Faster! Faster!"),
            Map.entry(75, "Duty Free Shop"),
            Map.entry(78, "Minigame Sub (8 Player)"),
            Map.entry(79, "On the Ice"),
            Map.entry(81, "Solo Mode Win"),
            Map.entry(94, "Bowser Intro"),
            Map.entry(95, "Star Get"),
            Map.entry(98, "DK Intro"),
            Map.entry(99, "Board Intro"),
            Map.entry(100, "Bowser Time!"),
            Map.entry(103, "New Record"),
            Map.entry(104, "Minigame Win"),
            Map.entry(105, "Minigame Lose"),
            Map.entry(106, "Tie"),
            Map.entry(108, "Bowser Castle Theme"),
            Map.entry(109, "The Koopa King Falls"),
            Map.entry(110, "Solo Mode Beaten")
    );
}
