package constants;

import java.util.Map;

public class MarioPartySongNames {

    public static final Map<Integer, String> MARIO_PARTY_5_TRACK_NAMES = Map.ofEntries(
            Map.entry(2, "Dream Party"),
            Map.entry(3, "Inside the Dream"),
            Map.entry(4, "Start of the Dream"),
            Map.entry(5, "Lots of Toys"),
            Map.entry(6, "Sky Presents"),
            Map.entry(7, "An Adventurer"),
            Map.entry(8, "Happy Seafloor"),
            Map.entry(9, "Space Match"),
            Map.entry(10, "In a Strange Land"),
            Map.entry(11, "Bowser's Dream"),
            Map.entry(12, "Tell Me How to Play!"),
            Map.entry(13, "Dream Country"),
            Map.entry(14, "Where's the Star?"),
            Map.entry(15, "Battle Mini-Game"),
            Map.entry(16, "Bowser Appears"),
            Map.entry(17, "Please, DK!"),
            Map.entry(18, "Doubtful Chance"),
            Map.entry(19, "Wiggler Transforms"),
            Map.entry(20, "Last Five Turns"),
            Map.entry(21, "Dream Finale"),
            Map.entry(24, "Koopa Kid Offspring"),
            Map.entry(25, "Dizzy Head"),
            Map.entry(26, "Bowser's Sour Grapes"),
            Map.entry(27, "What's Your Rank?"),
            Map.entry(28, "Bowser's Scheme"),
            Map.entry(29, "Where to Next?"),
            Map.entry(30, "Chase Bowser"),
            Map.entry(31, "Your Dream Comes True"),
            Map.entry(32, "Everybody's Dream"),
            Map.entry(35, "Tournament Minigame"),
            Map.entry(36, "Minigame Circuit"),
            Map.entry(37, "Battle Match"),
            Map.entry(38, "Sign Attack"),
            Map.entry(39, "How about a Card?"),
            Map.entry(40, "Card Party"),
            Map.entry(41, "Secret Garage"),
            Map.entry(43, "Burning Challenger"),
            Map.entry(44, "Knock em Out"),
            Map.entry(45, "Plunder"),
            Map.entry(46, "Rabbit"),
            Map.entry(48, "Ready, OK?"),
            Map.entry(49, "Battle Results"),
            Map.entry(50, "In Great Fear"),
            Map.entry(51, "In Calm Water"),
            Map.entry(52, "Exciting Walk"),
            Map.entry(53, "Everybody Party"),
            Map.entry(54, "Rolling About"),
            Map.entry(55, "Bustling Nosily"),
            Map.entry(57, "Nervous Tension"),
            Map.entry(58, "Danger Abounds"),
            Map.entry(59, "Midday Showdown"),
            Map.entry(60, "Move Happily"),
            Map.entry(61, "DK Chance!"),
            Map.entry(62, "Serious Competition"),
            Map.entry(63, "Bad Bowser Castle"),
            Map.entry(64, "Final Test"),
            Map.entry(65, "Big Bowser Battle!"),
            Map.entry(66, "Piranha Metal"),
            Map.entry(67, "Piranha Swing"),
            Map.entry(68, "Piranha Ballad"),
            Map.entry(69, "Dream Memories"),
            Map.entry(70, "Who's First?"),
            Map.entry(71, "You're the Star!"),
            Map.entry(72, "End of the Battle"),
            Map.entry(74, "We're the Champs"),
            Map.entry(75, "How Far?"),
            Map.entry(76, "Chain Chomp Rage"),
            Map.entry(77, "Exciting Walk (with Intro)"),
            Map.entry(78, "Everybody Party (Dinger Derby)"),
            Map.entry(79, "Rolling About (Defuse or Lose)"),
            Map.entry(80, "Nervous Tension (Revolving Fire)"),
            Map.entry(81, "Move Happily (with Intro)"),
            Map.entry(82, "Sign Attack (no Intro)"),
            Map.entry(83, "Rolling About (Flatiator)"),
            Map.entry(84, "Everybody Party (with Intro)"),
            Map.entry(85, "Rolling About (Later Skater)"),
            Map.entry(86, "Serious Competition (with Intro)"),
            Map.entry(87, "Bowser Laughs"),
            Map.entry(88, "Rolling About (Will Flower)"),
            Map.entry(89, "In Great Fear (Big Top Drop)"),
            Map.entry(90, "Please, DK! (without Intro)"),
            Map.entry(91, "Battle Mini-Game (without Intro)"),
            Map.entry(121, "Did It! Mini-Game"),
            Map.entry(122, "You Lost! Bummer"),
            Map.entry(123, "It's a Tie"),
            Map.entry(124, "End of Bowser's Dream"),
            Map.entry(126, "Machine Complete"),
            Map.entry(127, "The Star is Yours"),
            Map.entry(128, "A Bit of Happiness"),
            Map.entry(129, "A Lot of Happiness"),
            Map.entry(131, "Battle Wasteland"),
            Map.entry(133, "Start Battle"),
            Map.entry(138, "Confusion"),
            Map.entry(139, "Tiresome Bowser"),
            Map.entry(140, "You're Invincible")
    );

    public static final Map<Integer, String> MARIO_PARTY_6_TRACK_NAMES = Map.ofEntries(
            Map.entry(0, "Here We Go"),
            Map.entry(1, "Party Music"),
            Map.entry(2, "Setting Up"),
            Map.entry(3, "Time to Play"),
            Map.entry(4, "Brighton and Twila Song"),
            Map.entry(5, "Brighton Theme"),
            Map.entry(6, "Twila Theme"),
            Map.entry(7, "Options Menu"),
            Map.entry(8, "Whoop it Up"),
            Map.entry(9, "Mario Party 6"),
            Map.entry(10, "Block Star 1"),
            Map.entry(11, "Board Party"),
            Map.entry(12, "Star Space"),
            Map.entry(13, "Towering Treetop"),
            Map.entry(14, "Evening Treetop"),
            Map.entry(15, "E Gadd's Garage"),
            Map.entry(16, "Night at the Garage"),
            Map.entry(17, "Faire Square"),
            Map.entry(18, "Square at Night"),
            Map.entry(19, "Snowflake Lake"),
            Map.entry(20, "Snowy Night"),
            Map.entry(21, "Castaway Bay"),
            Map.entry(22, "Night on the Bay"),
            Map.entry(23, "Clockwork Castle"),
            Map.entry(24, "Night at the Castle"),
            Map.entry(25, "Duel/Battle"),
            Map.entry(26, "Battle Results"),
            Map.entry(27, "Bowser Theme"),
            Map.entry(28, "Bowser Theme (without Intro)"),
            Map.entry(29, "DK Theme"),
            Map.entry(30, "DK Theme (without Intro)"),
            Map.entry(31, "Round of Miracles"),
            Map.entry(32, "Boo Attack"),
            Map.entry(33, "Five Turns Left"),
            Map.entry(34, "Party's Over"),
            Map.entry(35, "Winner"),
            Map.entry(36, "Champ"),
            Map.entry(37, "Brighton's Explanation"),
            Map.entry(38, "Twila's Explanation"),
            Map.entry(39, "Getting a Star"),
            Map.entry(40, "Playing Together"),
            Map.entry(41, "Winning Together"),
            Map.entry(42, "Block Star 3"),
            Map.entry(43, "Block Star 2"),
            Map.entry(45, "Thirsty Gulch"),
            Map.entry(46, "Astro Avenue"),
            Map.entry(47, "Infernal Tower"),
            Map.entry(48, "Way to Go"),
            Map.entry(49, "Too Bad"),
            Map.entry(50, "Special Gift"),
            Map.entry(51, "Mini-Game Tour"),
            Map.entry(52, "Battle Bridge"),
            Map.entry(53, "Decathlon Park"),
            Map.entry(54, "Endurance Alley"),
            Map.entry(55, "Treetop Bingo"),
            Map.entry(56, "Really Long Road"),
            Map.entry(57, "Almost Endless Road"),
            Map.entry(58, "Up High"),
            Map.entry(59, "Pushing the Limit"),
            Map.entry(60, "100 Wins in a Row"),
            Map.entry(61, "Long Road"),
            Map.entry(64, "Warming Up"),
            Map.entry(65, "Insectiride Choose"),
            Map.entry(66, "Success"),
            Map.entry(67, "Winning"),
            Map.entry(68, "Losing"),
            Map.entry(69, "Bad News"),
            Map.entry(70, "Taking a Break"),
            Map.entry(71, "Maze Jam"),
            Map.entry(72, "Frantic"),
            Map.entry(73, "Jazzy"),
            Map.entry(74, "Doom and Gloom"),
            Map.entry(75, "Tenacious"),
            Map.entry(76, "Blissful"),
            Map.entry(77, "Pumped Up"),
            Map.entry(78, "Laid-back"),
            Map.entry(79, "Relaxed"),
            Map.entry(80, "Slam Dunk"),
            Map.entry(81, "Upbeat"),
            Map.entry(82, "Amusing"),
            Map.entry(83, "Slow and Steady"),
            Map.entry(84, "Fast and Furious"),
            Map.entry(85, "Night Duel"),
            Map.entry(86, "Time to Duel"),
            Map.entry(87, "Duel for Prizes"),
            Map.entry(88, "Gaming with Bowser"),
            Map.entry(89, "Gaming with DK"),
            Map.entry(90, "Seer Terror"),
            Map.entry(91, "Maze Manufactory"),
            Map.entry(92, "Star Bank"),
            Map.entry(93, "Quiz Master"),
            Map.entry(94, "Miracle Book"),
            Map.entry(95, "Speak Up"),
            Map.entry(96, "Quiz Song"),
            Map.entry(97, "Bowser Quiz"),
            Map.entry(99, "Well Done"),
            Map.entry(100, "Mic Question"),
            Map.entry(101, "Mic Question 2"),
            Map.entry(102, "Mic Question 3"),
            Map.entry(103, "Mic Question 4"),
            Map.entry(104, "Mic Question 5"),
            Map.entry(105, "Fun Times"),
            Map.entry(106, "Old School"),
            Map.entry(107, "Meadow Road"),
            Map.entry(108, "Dark Path"),
            Map.entry(109, "Magma Flows")
    );

    public static final Map<Integer, String> MARIO_PARTY_7_TRACK_NAMES = Map.ofEntries(
            Map.entry(0, "Let's Go"),
            Map.entry(1, "Mario Party Theme"),
            Map.entry(2, "Adventure Awaits"),
            Map.entry(3, "Set Sail for Fun"),
            Map.entry(4, "Cruise Choices"),
            Map.entry(5, "Dueling Range"),
            Map.entry(6, "Options Mode"),
            Map.entry(7, "The Last Hurrah"),
            Map.entry(8, "Many Thanks"),
            Map.entry(9, "Get This Party Started"),
            Map.entry(10, "Twinkle, Little Star"),
            Map.entry(11, "Sail the Canals"),
            Map.entry(12, "Climb the Peak"),
            Map.entry(13, "Park It"),
            Map.entry(14, "Neon Nation"),
            Map.entry(15, "Mill It Over"),
            Map.entry(16, "Inferno"),
            Map.entry(17, "Minigame Madness"),
            Map.entry(18, "It's a Duel"),
            Map.entry(19, "The Mic Shuffle"),
            Map.entry(20, "DK's Disco"),
            Map.entry(21, "The Bowser Boogie"),
            Map.entry(22, "Stop! Bowser Time!"),
            Map.entry(23, "Bowser's Rage"),
            Map.entry(24, "What's the Score?"),
            Map.entry(26, "Closing In"),
            Map.entry(27, "The Afterparty"),
            Map.entry(29, "Who's Will Win?"),
            Map.entry(30, "Hail to the King"),
            Map.entry(31, "Take Me to Partytown"),
            Map.entry(32, "Minigames at Dawn"),
            Map.entry(33, "Bowser's Invitation"),
            Map.entry(37, "The Free Play Sub"),
            Map.entry(38, "Volcano Peril"),
            Map.entry(39, "Pearl Hunt"),
            Map.entry(40, "Waterfall Duel"),
            Map.entry(41, "Decathalon Castle"),
            Map.entry(42, "King of the River"),
            Map.entry(44, "Tough Luck"),
            Map.entry(45, "Tough Luck Reprise"),
            Map.entry(46, "The Tough Luck Remix"),
            Map.entry(47, "Dreaming of Riches"),
            Map.entry(48, "The Motherlode"),
            Map.entry(49, "The Motherlode (without Intro)"),
            Map.entry(50, "Ready, Set, Fun"),
            Map.entry(51, "Lazy Day Lollygag"),
            Map.entry(52, "Keep it Up"),
            Map.entry(53, "Fun in the Sun"),
            Map.entry(54, "Skyward Bound"),
            Map.entry(55, "Don't Look Down"),
            Map.entry(56, "Slow and Steady"),
            Map.entry(57, "Darkness Rising"),
            Map.entry(58, "What a Mess!"),
            Map.entry(59, "Look Out!"),
            Map.entry(60, "Cool as a Cucumber"),
            Map.entry(61, "Watch Yourself"),
            Map.entry(62, "Without a Care"),
            Map.entry(64, "Time Grows Nigh"),
            Map.entry(65, "Jump!"),
            Map.entry(66, "Face-Off"),
            Map.entry(67, "Bowser's Revenge"),
            Map.entry(68, "Solo DK"),
            Map.entry(69, "DK for All!"),
            Map.entry(70, "High Noon"),
            Map.entry(71, "One Last Go"),
            Map.entry(72, "A Rare Minigame"),
            Map.entry(73, "Faster! Faster!"),
            Map.entry(75, "Happy Memories"),
            Map.entry(78, "Eight-Player Rumble"),
            Map.entry(79, "On the Ice"),
            Map.entry(81, "The Duel Ends"),
            Map.entry(94, "Trouble Brewing"),
            Map.entry(95, "A Star is Born"),
            Map.entry(96, "You Win"),
            Map.entry(97, "You Win More"),
            Map.entry(98, "Magic"),
            Map.entry(99, "Fun For All"),
            Map.entry(100, "An Angry Bowser"),
            Map.entry(103, "It's a New Record"),
            Map.entry(104, "Minigame Victory"),
            Map.entry(105, "Minigame Defeat"),
            Map.entry(106, "Minigame Draw"),
            Map.entry(108, "Bowser Castle Theme"),
            Map.entry(109, "The Koopa King Falls"),
            Map.entry(110, "A True Champion")
    );
}
