package constants;

public class MarioPartySongNames {

    public static final String[] MARIO_PARTY_5_TRACK_NAMES = {
            "Empty",
            "Everybody Party (Duplicate?)",
            "Title Screen",
            "Inside the Dream",
            "Start of the Dream",
            "Toy Dream",
            "Rainbow Dream",
            "Pirate Dream",
            "Undersea Dream",
            "Future Dream",
            "Sweet Dream",
            "Bowser Nightmare",
            "Tutorial",
            "Dream Country",
            "Star Location",
            "Duel/Battle",
            "Bowser",
            "DK",
            "Doubtful Chance",
            "Flutter",
            "Last 5 Turns",
            "Game Results",
            "Unused Beep",
            "Unused Beep",
            "Koopa Kid Offspring",
            "Dizzy Head",
            "Bowser's Sour Grapes",
            "What's Your Rank?",
            "Bowser's Scheme",
            "Where to Next?",
            "Chase Bowser",
            "Your Dream Comes True",
            "Everybody's Dream (Credits)",
            "Unused Beep",
            "Unused Beep",
            "Tournament Minigame",
            "Minigame Circuit",
            "Battle Match",
            "Sign Attack",
            "How about a Card?",
            "Card Party",
            "Super Duel Mode Garage",
            "Unused Beep",
            "Burning Challenger",
            "Knock em Out",
            "Plunder",
            "Rabbit",
            "Unused Beep",
            "Ready, OK?",
            "Minigame Results",
            "In Great Fear",
            "In Calm Water",
            "Exciting Walk",
            "Everybody Party",
            "Rolling About",
            "Bustling Nosily",
            "Unused Beep",
            "Nervous Tension",
            "Danger Abounds",
            "Midday Showdown",
            "Move Happily",
            "DK Chance!",
            "Serious Competition",
            "Bad Bowser Castle",
            "Final Test",
            "Big Bowser Battle!",
            "Pop Star Piranhas 1",
            "Pop Star Piranhas 2",
            "Pop Star Piranhas 3",
            "Dream Memories",
            "Who Won?",
            "Game Winner",
            "End of the Battle",
            "Unused Beep",
            "We're the Champs",
            "How Far?",
            "Chain Chomp",
            "Exciting Walk (with Intro)",
            "Everybody Party (with Intro)",
            "Rolling About (with Intro)",
            "Nervous Tension (with Intro)",
            "Move Happily (with Intro)",
            "Sign Attack (no Intro)",
            "Rolling About again?",
            "Everybody Party again?",
            "Rolling About again?",
            "Serious Competition with Intro",
            "Bowser Laughs",
            "Rolling About again?",
            "In Great Fear again?",
            "DK again?",
            "Battle/Duel again?",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Unused Beep",
            "Doubtful Chance again?",
            "Unused Beep",
            "Unused Beep",
            "Minigame Winner",
            "Minigame Lose",
            "Tie",
            "idk",
            "Unused Beep",
            "Machine Complete",
            "Star Get",
            "A Bit of Happiness",
            "A Lot of Happiness",
            "Unused Beep",
            "Battle Wasteland",
            "Idk",
            "Start Battle",
            "Jingle",
            "Idk",
            "Sign Attack Intro (for some reason)",
            "Star Get again?",
            "Ztar",
            "Bowser Intro"
    };

    public static final String[] MARIO_PARTY_6_TRACK_NAMES = {
            "Here We Go (Intro)",
            "Party Music (Title Screen)",
            "Setting Up (File Select)",
            "Time to Play (Main Menu)",
            "Brighton and Twila Song (Character Select)",
            "Brighton Theme",
            "Twila Theme",
            "Options Menu",
            "Whoop it Up",
            "Credits",
            "Slow and Steady Sped Up (Block Star)",
            "Board Party (Party Mode Intro)",
            "Star Space",
            "Towering Treetop",
            "Evening Treetop",
            "E Gadd's Garage",
            "Night at the Garage",
            "Faire Square",
            "Square at Night",
            "Snowflake Lake",
            "Snowy Night",
            "Castaway Bay",
            "Night on the Bay",
            "Clockwork Castle",
            "Night at the Castle",
            "Duel/Battle",
            "Duel/Battle (again?)",
            "Bowser Theme",
            "Bowser Theme 2",
            "DK Theme",
            "DK Theme 2",
            "Round of Miracles",
            "Pink Boo",
            "Last 5 Turns",
            "Party's Over",
            "Winner",
            "Champ",
            "Brighton's Explanation",
            "Twila's Explanation",
            "Star Get",
            "Playing Together",
            "Winning Together",
            "Slow and Steady Rave Party? (Block Star)",
            "Block Star Again",
            "Idk",
            "Thirsty Gulch",
            "Astro Avenue",
            "Infernal Tower",
            "Solo Mode Results",
            "Solo Mode Lose",
            "Special Gift",
            "Minigame Bus",
            "Battle Bridge",
            "Decathalon Park",
            "Endurance Alley",
            "Treetop Bingo",
            "Really Long Road",
            "Almost Endless Road",
            "Up High",
            "Pushing the Limit",
            "100 Wins in a Row",
            "Long Road",
            "Jingle",
            "Idk",
            "Minigame Explanation",
            "Insectiride Choose",
            "New Record",
            "Minigame Winner",
            "Losing",
            "Tie",
            "Turn Results",
            "E Gadd Maze",
            "Frantic",
            "Jazzy",
            "Doom and Gloom",
            "Tenacious",
            "Blissful",
            "Pumped Up",
            "Laid-back",
            "Relaxed",
            "Slam Dunk",
            "Upbeat",
            "Amusing",
            "Slow and Steady",
            "Fast and Furious",
            "Night Duel",
            "Time to Duel",
            "Duel for Prizes",
            "Gaming with Bowser",
            "Gaming with DK",
            "Seer Terror",
            "Maze Manufactory",
            "Star Bank",
            "Quiz Master",
            "Miracle Book",
            "Speak Up",
            "Quiz Song",
            "Bowser Quiz",
            "Idk",
            "Well Done",
            "Mic Question",
            "Mic Question 2",
            "Mic Question 3",
            "Mic Question 4",
            "Mic Question 5",
            "Fun Times",
            "Old School",
            "Meadow Road",
            "Dark Path"
    };

    public static final String[] MARIO_PARTY_7_TRACK_NAMES = {
            "Intro",
            "Title Screen",
            "File Select",
            "Main Menu",
            "Character Select",
            "Solo Mode",
            "Options Mode",
            "The Last Hurrah",
            "Credits",
            "Party Mode Intro (start)",
            "Star Location",
            "Grand Canal",
            "Pagoda Peak",
            "Pyramid Park",
            "Neon Heights",
            "Windmillville",
            "Bowser's Enchanted Inferno",
            "Battle Game",
            "Duel",
            "Mic Game",
            "DK",
            "Bowser",
            "Bowser Time",
            "Bowser Theme 2",
            "Minigame Results",
            "Drumbeat?",
            "Last 4 Turns",
            "Game Results",
            "Drumbeat?",
            "Who's the Winner?",
            "Hail to the King",
            "Take me to Partytown",
            "Game Start (No Intro)",
            "Bowser's Invitation",
            "Idk",
            "Drumbeat",
            "Drumbeat",
            "Minigame Sub",
            "Volcano Peril",
            "Pearl Hunt",
            "Waterfall Duel",
            "Decathalon Castle",
            "King of the River",
            "Drumbeat",
            "King of the River 1",
            "King of the River 2",
            "King of the River 3",
            "King of the River Lose",
            "King of the River Win",
            "King of the River Win (no intro)",
            "Minigame Explanation",
            "Lazy Day Lollygag",
            "Keep it Up",
            "Fun in the Sun",
            "Skyward Bound",
            "Don't Look Down",
            "Slow and Steady",
            "Darkness Rising",
            "What a Mess!",
            "Look Out!",
            "Cool as a Cucumber",
            "Watch Yourself",
            "Without a Care (Mic Game)",
            "Drumbeat",
            "Time Grows Nigh",
            "Jump!",
            "Face-Off (Bowser Singleplayer)",
            "Bowser Multiplayer Game",
            "DK Singleplayer",
            "DK Multiplayer",
            "High Noon",
            "One Last Go",
            "Rare Minigame",
            "Faster! Faster!",
            "Drumbeat",
            "Duty Free Shop",
            "Drumbeat",
            "Drumbeat",
            "Minigame Sub (8 Player)",
            "On the Ice",
            "Drumbeat",
            "Solo Mode Win",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Drumbeat",
            "Unused Beep",
            "Unused Beep",
            "Jingle",
            "Bowser Intro",
            "Star Get",
            "Jingle",
            "Jingle",
            "DK Intro",
            "Board Intro",
            "Bowser Time!",
            "Unused Beep",
            "Unused Beep",
            "New Record",
            "Minigame Win",
            "Minigame Lose",
            "Tie",
            "Jingle",
            "Bowser Castle Theme",
            "The Koopa King Falls"
    };
}
